[FBD-8] 새로운 Access Token 발행 컨트롤러 개발
friendly-calendar/FC-Back pull request #7
Opened 2023-07-14 18:14 UTC by dokdogalmaegi

2023-07-14 18:17 UTC, dokdogalmaegi commented on build.gradle.kts
> +	id("org.asciidoctor.jvm.convert") version "3.3.2"
이전 restdocs 머지에서 누락된 id 추가

2023-07-18 04:33 UTC, Ho-Ya-Ho commented
@dokdogalmaegi 님,
코드 리뷰하였습니다. 확인부탁드리겠습니다 😀

2023-07-18 04:34 UTC, Ho-Ya-Ho requested changes

2023-07-18 04:34 UTC, Ho-Ya-Ho commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +    fun refreshToken(@RequestBody params: HashMap<String, Object>, @RequestHeader("Authorization") authorization: String): ResponseDto<Any> {
Kotlin에서는 Object 대신 Any타입을 사용해 보는건 어떨까요??

2023-07-18 04:34 UTC, Ho-Ya-Ho commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +            ResponseDto.fail(data = null, ErrorCode.INTERNAL_SERVER)
동일한 Exception에 대한 catch가 2개인데 확인부탁드리겠습니다!

2023-07-18 10:20 UTC, dokdogalmaegi commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +    fun refreshToken(@RequestBody params: HashMap<String, Object>, @RequestHeader("Authorization") authorization: String): ResponseDto<Any> {
강호님 리뷰 주신 것 처럼 Kotlin 의 원시타입 최상위 타입인 Any로 변경하였습니다.
확인 부탁드립니다!

2023-07-18 10:21 UTC, dokdogalmaegi commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +            ResponseDto.fail(data = null, ErrorCode.INTERNAL_SERVER)
잘못 선언된 Exception 이었습니다.
꼼꼼한 확인 감사드립니다!
현재는 수정 완료하였으며, 확인 부탁드리겠습니다.

2023-07-18 10:21 UTC, dokdogalmaegi commented
@Ho-Ya-Ho 님,
리뷰 주신 내용 모두 적용 완료하였습니다.
다시 한번 리뷰 부탁드립니다~!
@csbiy

2023-07-18 12:43 UTC, Ho-Ya-Ho commented
@dokdogalmaegi 님 
리뷰 결과 이견 없습니다. 수고하셨습니다😀

@csbiy 님,
리뷰 부탁드리겠습니다.

2023-07-19 23:21 UTC, csbiy reviewed
@dokdogalmaegi 님 리뷰완료하였습니다!
추가적으로 여유가되신다면 test코드를 작성해보는건어떨가요?

예를들면 refresh token으로  access token이 만료되었을때 body에 발급한 access token이 잘들어있는지 정상 케이스만이라도 테스트를 추가해보면 좋을것같습니다!🙂

2023-07-19 23:21 UTC, csbiy commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +                        throw Exception("Not matched username")
최상위예외인 Exception보다 좀더 에러를알기쉬운 IllegalArgumentException과 같은 예외를 사용하는건어떨까요?

2023-07-19 23:21 UTC, csbiy commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +        } catch (otherException: Exception) {
전체예외를 잡아서 처리해주는 부분은 저희가 만든 ControllerAdvice에서 처리해줄테니 이부분은빠져도될것같습니다!

2023-07-20 02:25 UTC, dokdogalmaegi commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +        } catch (otherException: Exception) {
@csbiy 님,
해당 건은 Controller에서 처리하는 Catch문을 제거하고, ControllerAdvice에서의 처리는 @Ho-Ya-Ho 님께서 https://friendly-calendar.atlassian.net/browse/FBD-7 이슈를 통해 처리하시기로 구두로 논의 되었습니다.
Catch 제거 후 다시 댓글 드리겠습니다.

2023-07-20 11:13 UTC, dokdogalmaegi commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +                        throw Exception("Not matched username")
조언 주신 IllegalArgumentException 으로 교체 완료하였습니다.

2023-07-20 11:13 UTC, dokdogalmaegi commented on src/main/kotlin/com/friendly/calendar/controller/TokenRefreshController.kt
> +        } catch (otherException: Exception) {
Catch 제거 완료하였습니다

2023-07-20 23:52 UTC, merged